const ELEMENT_WIDTH = 120;
const WIRE_LENGTH = 20;

export const createDemultiplexer = (id, type, x, y) => {
  // DEMUX 1:2
  if (type === "DEMUX2") {
    const height = 60;
    const width = 100;
    return {
      id,
      type,
      x,
      y,
      width,
      height,
      inputCount: 2,
      inputs: [
        {
          id: `${id}-input-0`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: -10,
          wireEndX: -width / 2,
          wireEndY: -10,
          value: 0,
          inverted: false,
          connected: false,
          label: "I",
        },
        {
          id: `${id}-input-1`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: 10,
          wireEndX: -width / 2,
          wireEndY: 10,
          value: 0,
          inverted: false,
          connected: false,
          label: "S",
        },
      ],
      outputs: [
        {
          id: `${id}-output-0`,
          localX: width / 2,
          localY: -10,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: -10,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y0",
        },
        {
          id: `${id}-output-1`,
          localX: width / 2,
          localY: 10,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: 10,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y1",
        },
      ],
    };
  }

  // DEMUX 1:4
  if (type === "DEMUX4") {
    const height = 100;
    const width = 120;
    return {
      id,
      type,
      x,
      y,
      width,
      height,
      inputCount: 3,
      inputs: [
        {
          id: `${id}-input-0`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: -30,
          wireEndX: -width / 2,
          wireEndY: -30,
          value: 0,
          inverted: false,
          connected: false,
          label: "I",
        },
        {
          id: `${id}-input-1`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: -10,
          wireEndX: -width / 2,
          wireEndY: -10,
          value: 0,
          inverted: false,
          connected: false,
          label: "S0",
        },
        {
          id: `${id}-input-2`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: 10,
          wireEndX: -width / 2,
          wireEndY: 10,
          value: 0,
          inverted: false,
          connected: false,
          label: "S1",
        },
      ],
      outputs: [
        {
          id: `${id}-output-0`,
          localX: width / 2,
          localY: -30,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: -30,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y0",
        },
        {
          id: `${id}-output-1`,
          localX: width / 2,
          localY: -10,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: -10,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y1",
        },
        {
          id: `${id}-output-2`,
          localX: width / 2,
          localY: 10,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: 10,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y2",
        },
        {
          id: `${id}-output-3`,
          localX: width / 2,
          localY: 30,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: 30,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y3",
        },
      ],
    };
  }

  // DEMUX 1:8
  if (type === "DEMUX8") {
    const height = 180;
    const width = 140;
    return {
      id,
      type,
      x,
      y,
      width,
      height,
      inputCount: 4,
      inputs: [
        {
          id: `${id}-input-0`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: -70,
          wireEndX: -width / 2,
          wireEndY: -70,
          value: 0,
          inverted: false,
          connected: false,
          label: "I",
        },
        {
          id: `${id}-input-1`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: -50,
          wireEndX: -width / 2,
          wireEndY: -50,
          value: 0,
          inverted: false,
          connected: false,
          label: "S0",
        },
        {
          id: `${id}-input-2`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: -30,
          wireEndX: -width / 2,
          wireEndY: -30,
          value: 0,
          inverted: false,
          connected: false,
          label: "S1",
        },
        {
          id: `${id}-input-3`,
          localX: -width / 2 - WIRE_LENGTH,
          localY: -10,
          wireEndX: -width / 2,
          wireEndY: -10,
          value: 0,
          inverted: false,
          connected: false,
          label: "S2",
        },
      ],
      outputs: [
        {
          id: `${id}-output-0`,
          localX: width / 2,
          localY: -70,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: -70,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y0",
        },
        {
          id: `${id}-output-1`,
          localX: width / 2,
          localY: -50,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: -50,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y1",
        },
        {
          id: `${id}-output-2`,
          localX: width / 2,
          localY: -30,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: -30,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y2",
        },
        {
          id: `${id}-output-3`,
          localX: width / 2,
          localY: -10,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: -10,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y3",
        },
        {
          id: `${id}-output-4`,
          localX: width / 2,
          localY: 10,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: 10,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y4",
        },
        {
          id: `${id}-output-5`,
          localX: width / 2,
          localY: 30,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: 30,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y5",
        },
        {
          id: `${id}-output-6`,
          localX: width / 2,
          localY: 50,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: 50,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y6",
        },
        {
          id: `${id}-output-7`,
          localX: width / 2,
          localY: 70,
          wireEndX: width / 2 + WIRE_LENGTH,
          wireEndY: 70,
          value: 0,
          connected: false,
          inverted: false,
          label: "Y7",
        },
      ],
    };
  }

  return null;
};
